### PR TITLE
Add support for multiple license selection

### PR DESCRIPTION
**Pull request by KShivendu**
Allows users to choose multiple licenses for their projects.

### CODE REVIEW

**Comment by progval** [comment]
Not tested but the code looks good. I'll check it out tomorrow.

Could you add a couple of cypress tests?

**Comment by progval** [comment]
> Select license only when enter key is pressed

Er... now that would be really confusing for people who don't know they are expected to press Enter while in the middle of a form

**Comment by KShivendu** [comment]
> Er... now that would be really confusing for people who don't know they are expected to press Enter while in the middle of a form

Okay looks like I misinterpreted this: 
```
I like the simplicity. Atfirst I felt uneasy with having to tab (or click) to leave the license field's focus, then tab/click back to it; but then I noticed pressing Enter worked as well. Not sure what can be done about this.
```

Could you please elaborate on what you mean exactly?

**Comment by progval** [comment]
I mean that, as a new user looking at the form, I wouldn't know how to input several licenses. Eventually it is obvious but only after inserting the first license and moving the focus away from the license field (with either Tab, Enter, or a click).

Supporting Tab itself is good so it shouldn't be removed; but I feel there should be a way to make it clear to new users that it's an option.

I could be wrong though. It may be fine to leave it like what you did initially. Or maybe just changing the label to "License(s)" to make it clear it is supported, and users should be able figure it out.

**Comment by KShivendu** [comment]
@progval ^

**Pull request merged**
